-- Havenzen Supabase/PostgreSQL schema.
-- Run this in Supabase SQL Editor before importing converted data.

drop view if exists latest_records;
drop table if exists driver_earnings cascade;
drop table if exists notifications cascade;
drop table if exists password_reset_tokens cascade;
drop table if exists system_logs cascade;
drop table if exists bookings cascade;
drop table if exists locations cascade;
drop table if exists vehicle_trips cascade;
drop table if exists vehicle_schedules cascade;
drop table if exists driver_availability cascade;
drop table if exists vehicles cascade;
drop table if exists admins cascade;
drop table if exists customers cascade;
drop table if exists drivers cascade;
drop table if exists routes cascade;
drop table if exists users cascade;

create table users (
  user_id integer generated by default as identity primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  role varchar(20) not null default 'passenger'
    check (role in ('passenger', 'driver', 'admin'))
);

create table routes (
  route_id integer generated by default as identity primary key,
  route_name varchar(100) not null,
  stops jsonb not null,
  fare numeric(10,2),
  distance_km numeric(10,2),
  travel_minutes integer not null default 0,
  created_at timestamp not null default current_timestamp
);

create table admins (
  admin_id integer generated by default as identity primary key,
  user_id integer not null unique references users(user_id) on delete cascade on update cascade,
  full_name varchar(100) not null,
  email varchar(255),
  phone_number varchar(20),
  profile_picture varchar(255),
  address text,
  created_at timestamp not null default current_timestamp,
  last_login timestamp
);

create table customers (
  customer_id integer generated by default as identity primary key,
  user_id integer not null unique references users(user_id) on delete cascade on update cascade,
  full_name varchar(100) not null,
  email varchar(255),
  phone_number varchar(20),
  profile_picture varchar(255),
  address text,
  created_at timestamp not null default current_timestamp,
  last_login timestamp
);

create table drivers (
  driver_id integer generated by default as identity primary key,
  user_id integer not null unique references users(user_id) on delete cascade on update cascade,
  full_name varchar(100) not null,
  email varchar(255),
  phone_number varchar(20),
  profile_picture varchar(255),
  license_number varchar(50),
  license_expiry date,
  license_class varchar(20),
  license_front_image varchar(255),
  license_back_image varchar(255),
  years_experience integer,
  emergency_contact varchar(100),
  emergency_phone varchar(20),
  address text,
  is_online boolean not null default false,
  current_location point,
  created_at timestamp not null default current_timestamp,
  last_login timestamp
);

create table vehicles (
  vehicle_id integer generated by default as identity primary key,
  vehicle_name varchar(50) not null,
  license_plate varchar(15) not null unique,
  vehicle_type varchar(50),
  vehicle_color varchar(50),
  vehicle_model varchar(100),
  seat_capacity integer not null default 0,
  driver_id integer references users(user_id) on delete set null,
  route_id integer references routes(route_id) on delete set null,
  return_route_id integer references routes(route_id) on delete set null,
  status varchar(20) default 'active'
    check (status in ('active', 'inactive', 'maintenance')),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table driver_availability (
  availability_id integer generated by default as identity primary key,
  driver_id integer not null references users(user_id) on delete cascade,
  available_from time not null,
  available_to time not null,
  day_of_week varchar(20) not null
    check (day_of_week in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
  is_active boolean default true,
  created_at timestamp not null default current_timestamp
);

create table vehicle_schedules (
  schedule_id integer generated by default as identity primary key,
  vehicle_id integer not null references vehicles(vehicle_id) on delete cascade,
  driver_id integer references users(user_id) on delete set null,
  route_id integer not null references routes(route_id) on delete cascade,
  return_route_id integer references routes(route_id) on delete set null,
  departure_time time not null,
  active_days jsonb not null,
  layover_minutes integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table vehicle_trips (
  trip_id integer generated by default as identity primary key,
  schedule_id integer not null references vehicle_schedules(schedule_id) on delete cascade,
  vehicle_id integer not null references vehicles(vehicle_id) on delete cascade,
  driver_id integer references users(user_id) on delete set null,
  route_id integer not null references routes(route_id) on delete cascade,
  direction varchar(20) not null default 'outbound'
    check (direction in ('outbound', 'return')),
  scheduled_departure_at timestamp not null,
  actual_departure_at timestamp,
  arrival_reported_at timestamp,
  completed_at timestamp,
  trip_status varchar(20) not null default 'scheduled'
    check (trip_status in ('scheduled', 'boarding', 'in_transit', 'completed', 'cancelled')),
  seat_capacity_snapshot integer not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique (schedule_id, direction, scheduled_departure_at)
);

create table bookings (
  booking_id integer generated by default as identity primary key,
  passenger_id integer not null references users(user_id) on delete cascade,
  pickup_location varchar(255) not null,
  pickup_lat numeric(10,8),
  pickup_lng numeric(11,8),
  dropoff_location varchar(255) not null,
  dropoff_lat numeric(10,8),
  dropoff_lng numeric(11,8),
  status varchar(20) default 'pending'
    check (status in ('pending', 'confirmed', 'in_progress', 'completed', 'denied', 'cancelled')),
  requested_time timestamp not null,
  vehicle_id integer references vehicles(vehicle_id) on delete set null,
  route_id integer references routes(route_id) on delete set null,
  trip_id integer references vehicle_trips(trip_id) on delete set null,
  scheduled_departure_at timestamp,
  passenger_count integer not null default 1,
  baggage_count integer not null default 0,
  boarding_status varchar(30) not null default 'scheduled'
    check (boarding_status in ('scheduled', 'vehicle_arrived', 'boarded', 'no_show', 'dropped_off')),
  arrival_reported_at timestamp,
  boarding_deadline_at timestamp,
  boarded_at timestamp,
  dropped_off_at timestamp,
  no_show_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  fare numeric(10,2) default 0.00,
  fare_estimate numeric(10,2) default 0.00,
  notes text,
  rating smallint,
  driver_id integer,
  accepted_at timestamp,
  rejected_at timestamp,
  driver_notes text
);

create table driver_earnings (
  earning_id integer generated by default as identity primary key,
  driver_id integer not null references users(user_id) on delete cascade,
  booking_id integer not null references bookings(booking_id) on delete cascade,
  amount numeric(10,2) not null,
  earning_date date not null,
  status varchar(20) default 'pending'
    check (status in ('pending', 'paid')),
  created_at timestamp not null default current_timestamp
);

create table locations (
  location_id integer generated by default as identity primary key,
  vehicle_id integer not null references vehicles(vehicle_id) on delete cascade,
  latitude numeric(10,8) not null,
  longitude numeric(11,8) not null,
  timestamp timestamp default current_timestamp
);

create table notifications (
  id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade,
  type varchar(100) not null,
  message text not null,
  data jsonb,
  is_read boolean not null default false,
  created_at timestamp not null default current_timestamp
);

create table password_reset_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade,
  token varchar(64) not null unique,
  expiry_date timestamp not null,
  created_at timestamp not null default current_timestamp
);

create table system_logs (
  log_id integer generated by default as identity primary key,
  user_id integer references users(user_id) on delete set null,
  action varchar(255) not null,
  description text,
  ip_address varchar(45),
  user_agent text,
  created_at timestamp not null default current_timestamp
);

create index idx_bookings_passenger_id on bookings(passenger_id);
create index idx_bookings_status on bookings(status);
create index idx_bookings_requested_time on bookings(requested_time);
create index idx_bookings_driver_id on bookings(driver_id);
create index idx_bookings_trip_id on bookings(trip_id);
create index idx_bookings_scheduled_departure_at on bookings(scheduled_departure_at);
create index idx_bookings_boarding_status on bookings(boarding_status);
create index idx_driver_availability_driver_id on driver_availability(driver_id);
create index idx_driver_earnings_driver_id on driver_earnings(driver_id);
create index idx_driver_earnings_date on driver_earnings(earning_date);
create index idx_locations_vehicle_id on locations(vehicle_id);
create index idx_locations_timestamp on locations(timestamp);
create index idx_password_reset_tokens_user_id on password_reset_tokens(user_id);
create index idx_password_reset_tokens_expiry on password_reset_tokens(expiry_date);
create index idx_system_logs_created_at on system_logs(created_at);
create index idx_system_logs_user_id on system_logs(user_id);
create index idx_vehicle_schedules_vehicle_id on vehicle_schedules(vehicle_id);
create index idx_vehicle_schedules_driver_id on vehicle_schedules(driver_id);
create index idx_vehicle_schedules_route_id on vehicle_schedules(route_id);
create index idx_vehicle_schedules_active on vehicle_schedules(is_active);
create index idx_vehicle_trips_vehicle_date on vehicle_trips(vehicle_id, scheduled_departure_at);
create index idx_vehicle_trips_driver_date on vehicle_trips(driver_id, scheduled_departure_at);
create index idx_vehicle_trips_route_date on vehicle_trips(route_id, scheduled_departure_at);
create index idx_vehicle_trips_status on vehicle_trips(trip_status);
create index idx_vehicles_driver_id on vehicles(driver_id);
create index idx_vehicles_status on vehicles(status);

create or replace view latest_records as
select location_id, vehicle_id, latitude, longitude, timestamp
from locations
order by timestamp desc
limit 10;
